### ISSUE TITLE
Website updates for launch

### ISSUE THREAD

**Issue by RothAndrew** [milspaceclub/website#4]
- [x] Update landing page (logos and colors)
	- [x] 	"swoosh" logo (big) in hero instead of white text
	- [x] 	Something space themed for the background instead of the purple triangles (or change the colors of the existing triangles)
	- [x] Color scheme according to style guide (guide is in google drive)
- [x] Update signup link to “member join form” (free version)
- [x] Board roster
- [x] Link Bylaws
- [x] Link Constitution
- [x] Intro statement on home page (can grab from the facebook page)
- [x] Facebook link
- [x] Events Calendar
- [x] Legal disclaimer (in footer of every page)

**Comment by krich275** [comment]
Join as a member Form Link: https://forms.gle/3zzuRioefkpKgzDy9

**Comment by RothAndrew** [comment]
Sections (Link Tree):

- Home
- About Us
	- Board Roster
- Docs
	- Constitution
	- Bylaws
- Events

**Comment by krich275** [comment]
Style Guide - color codes
https://docs.google.com/document/d/1Hgx_T9G9_DYAkqmO5fxC1Eb2Gzect669h9KrenbUSFk/edit?usp=sharing

**Comment by krich275** [comment]
style guide in marketing on shared drive

**Comment by RothAndrew** [comment]
Events we already know we want on the calendar:

- Brunch on Sunday March 10 (Andy to coordinate)
- Launch social on March 20 at Proud Bird
- Top Golf (Date TBD)

Ideas for brunch:
- Uncle Bill's Pancake House
- Sloopy's
- King's Hawaiian

**Comment by RothAndrew** [comment]
Shareable link to public google calendar: https://calendar.google.com/calendar/u/3?cid=bWlsc3BhY2VjbHViQGdtYWlsLmNvbQ

**Comment by RothAndrew** [comment]
Calling this one done for right now. Will open new issue with further changes.

**Comment by krich275** [comment]
This all looks good - a small wording addition: 

on the landing page - under the blurb about the club, if we can add a new paragraph with a line break between them, just above the "join now button" 

Join now and receive a FREE membership trial, now through July 31, 2024!

**Comment by angrybunn** [comment]
I will create a new small logo to upload instead of the small rocket hands icon for visibility on tab.

**Comment by angrybunn** [comment]
connect with us on Facebook link on every page

**Comment by angrybunn** [comment]
Courtney's name might be misspelled double check I believe it's Travaglini

**Comment by RothAndrew** [comment]
Updated Courtney's name and added the new line to the home page. Facebook link on every page will be a bit harder to do in a way that looks nice. Would you want it at the top in the navbar or at the bottom in the footer?

**Comment by krich275** [comment]
Top nav bar would work!

**Comment by RothAndrew** [comment]
Added facebook link to top bar. I'll look into switching it to the icon rather than the word "facebook", I think that would look a bit nicer.

**Comment by RothAndrew** [comment]
Changed it to the facebook logo. Let me know if you like that better or if you want it back to the word "facebook". If you're happy with it and ready for it to go live go back over to the pull request #5 and click the green button that says "squash and merge"

**Comment by krich275** [comment]
the font on the landing page for the blurb turned back to black with the update and is hard to read, can we correct that back to white text?
